version: '3'
services:
  database:
    image: "postgres:alpine"
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./db_data/:/var/lib/postgresql/data
  beryll:
    image: "chrissound/berylliumblueberry:latest"
    ports:
     - "3001:3001"
    volumes:
      - ./data/:/data/data
